cmake -B Build/iOS -D IOS=ON -G Xcode \
    -D JSRUNTIMEHOST_POLYFILL_URL=OFF \
    -D JSRUNTIMEHOST_POLYFILL_ABORT_CONTROLLER=OFF \
    -D JSRUNTIMEHOST_POLYFILL_WEBSOCKET=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVECAMERA=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVECAPTURE=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVEENGINE_WEBP=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVEOPTIMIZATIONS=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVETRACING=OFF \
    -D BABYLON_NATIVE_PLUGIN_NATIVEXR=OFF \
    -D BABYLON_NATIVE_PLUGIN_TESTUTILS=OFF \
    -D BABYLON_NATIVE_POLYFILL_CANVAS=OFF \

