name: CI

on:
  push:
    branches: [master, rework-thread-model-perf]
  pull_request:
    branches: [master]

jobs:
  Ubuntu_Clang_JSC:
    uses: ./.github/workflows/build-linux.yml
    with:
      cc: clang
      cxx: clang++
      js-engine: JavaScriptCore

  Ubuntu_GCC_JSC:
    uses: ./.github/workflows/build-linux.yml
    with:
      cc: gcc
      cxx: g++
      js-engine: JavaScriptCore